{"name": "test_is_prime_2_7", "status": "failed", "statusDetails": {"message": "AssertionError: True is not false", "trace": "self = <testcase.test_func.TestMyFunc testMethod=test_is_prime_2_7>, a = 7\n\n    @data(5, 7,8,-2,0,1)\n    def test_is_prime(self, a):    #测试用例以test_开头\n        ''' test method is_prime(number) '''\n        print(\"is_prime\")\n>       self.assertFalse(is_prime(a))\nE       AssertionError: True is not false\n\ntestcase\\test_func.py:37: AssertionError"}, "description": " test method is_prime(number) ", "attachments": [{"name": "stdout", "source": "88fdddeb-9d96-496d-8668-40cfb310de2f-attachment.txt", "type": "text/plain"}], "start": 1572531712061, "stop": 1572531712062, "uuid": "b8945251-f8dd-4d5f-b8e0-4ea0e5fe97aa", "historyId": "888f1014fcf5f3bdaa559ec74f84940f", "testCaseId": "a26771bab807c1b4fc9ecdfd4e5e6780", "fullName": "testcase.test_func.TestMyFunc#test_is_prime_2_7", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "TestMyFunc"}, {"name": "host", "value": "LeeYatyi"}, {"name": "thread", "value": "12480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_func"}]}